version: '3.7'
services:
  whatsgrambot:
    build:
      context: .
      args:
        PORT: ${PORT}
    ports:
    - "${HOST_PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - TZ=Asia/Jerusalem
    platform: linux/amd64
    restart: always
    container_name: ${CONTAINER_NAME}
    volumes:
      - ./:/whatsgrambot
    command: ["python", "main.py"]
